# Generated by Django 5.1 on 2024-08-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco_pagina', models.CharField(max_length=150)),
                ('qtd_integrantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_album', models.CharField(max_length=150)),
                ('ano_lancamento', models.DateField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.artista')),
            ],
        ),
    ]
