# Generated by Django 5.1 on 2024-08-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
